### ISSUE TITLE
Cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by solracsf** [bhuanand/rps-rfs-configuration#1]
```
# python3 rps.py ens10 --configure-rfs

Number of CPU(s) available.. : 2
Number of queues in interface 'ens10'.. : 1
Traceback (most recent call last):
  File "rps.py", line 126, in <module>
    configure_rps(args.iface)
  File "rps.py", line 93, in configure_rps
    for q, irq in irq_cpu_map(iface).items():
  File "rps.py", line 51, in irq_cpu_map
    if re.search(iface, line) and re.search(qtype, line):
  File "/usr/lib/python3.8/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
```

**Comment by bhuanand** [comment]
I had written & used the script with Python 2.x version. Looks like need to update the script to Python 3.
Can you try with 2.x version and see if it works?

**Comment by solracsf** [comment]
Yes it does work:

```
python rps.py eth0 --configure-rfs
Number of CPU(s) available.. : 3
Number of queues in interface 'eth0'.. : 1
Mapping the corresponding TX queue to same CPU(s) as RX queue
Setting /proc/sys/net/core/rps_sock_flow_entries with value 32768
Configuring /sys/class/net/eth0/queues/rx-0/rps_flow_cnt with value 10922
```

Shouldn't `rps_flow_cnt` be the same value than `rps_sock_flow_entries` here?
As per https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/performance_tuning_guide/network-rfs

**Comment by bhuanand** [comment]
Yes. its a bug!

In the code,  Calculating `rps_flow_cnt` as `rps_flow_cnt = rps_sock_flow_entries / numcpus()` - which is wrong.
It should be `rps_flow_cnt = rps_sock_flow_entries  / len(iface_queues(iface, qtype="rx"))`
